import { SoundEffect } from './types';

export const defaultSoundEffects: SoundEffect[] = [
  // Retro / Game Sound Effects
  {
    id: 'retro-laser',
    name: 'Laser Fire',
    khmerName: 'បាញ់កាំរស្មី Laser',
    category: 'game',
    icon: 'Zap',
    color: 'emerald',
    keyTrigger: 'Q',
    params: {
      waveform: 'sawtooth',
      startFreq: 1300,
      endFreq: 80,
      duration: 0.18,
      attack: 0.0,
      decay: 0.7,
      sustain: 0.05,
      release: 0.05,
      volume: 0.75,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 3000,
      filterSweep: true,
      distortion: 0.1,
    }
  },
  {
    id: 'retro-coin',
    name: 'Retro Coin',
    khmerName: 'រើសកាក់មាស',
    category: 'game',
    icon: 'Coins',
    color: 'amber',
    keyTrigger: 'W',
    params: {
      waveform: 'square',
      startFreq: 850,
      endFreq: 1350,
      duration: 0.16,
      attack: 0.01,
      decay: 0.5,
      sustain: 0.4,
      release: 0.08,
      volume: 0.65,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 8000,
      filterSweep: false,
      distortion: 0.0,
    }
  },
  {
    id: 'retro-jump',
    name: 'Jump Bounce',
    khmerName: 'លោតផ្លោះ',
    category: 'game',
    icon: 'ArrowUp',
    color: 'cyan',
    keyTrigger: 'E',
    params: {
      waveform: 'triangle',
      startFreq: 160,
      endFreq: 750,
      duration: 0.15,
      attack: 0.02,
      decay: 0.8,
      sustain: 0.1,
      release: 0.05,
      volume: 0.8,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 5000,
      filterSweep: false,
      distortion: 0.0,
    }
  },
  {
    id: 'retro-powerup',
    name: 'Power Up',
    khmerName: 'តម្លើងថាមពល',
    category: 'game',
    icon: 'Sparkles',
    color: 'purple',
    keyTrigger: 'R',
    params: {
      waveform: 'triangle',
      startFreq: 180,
      endFreq: 1400,
      duration: 0.42,
      attack: 0.15,
      decay: 0.7,
      sustain: 0.6,
      release: 0.12,
      volume: 0.7,
      vibratoFreq: 14,
      vibratoDepth: 40,
      filterFreq: 6000,
      filterSweep: false,
      distortion: 0.05,
    }
  },
  {
    id: 'retro-explosion',
    name: 'Explosion',
    khmerName: 'ផ្ទុះសំបើម',
    category: 'game',
    icon: 'Bomb',
    color: 'rose',
    keyTrigger: 'T',
    params: {
      waveform: 'noise',
      startFreq: 0,
      endFreq: 0,
      duration: 0.75,
      attack: 0.01,
      decay: 0.85,
      sustain: 0.05,
      release: 0.25,
      volume: 0.95,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 1000,
      filterSweep: true,
      distortion: 0.45,
    }
  },
  {
    id: 'retro-hit',
    name: 'Impact Hit',
    khmerName: 'ប៉ះទង្គិច / រងរបួស',
    category: 'game',
    icon: 'ShieldAlert',
    color: 'orange',
    keyTrigger: 'Y',
    params: {
      waveform: 'noise',
      startFreq: 0,
      endFreq: 0,
      duration: 0.12,
      attack: 0.0,
      decay: 0.9,
      sustain: 0.0,
      release: 0.05,
      volume: 0.85,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 450,
      filterSweep: true,
      distortion: 0.5,
    }
  },
  {
    id: 'retro-levelup',
    name: 'Level Up',
    khmerName: 'ឡើងវគ្គថ្មី',
    category: 'game',
    icon: 'Trophy',
    color: 'yellow',
    keyTrigger: 'U',
    params: {
      waveform: 'triangle',
      startFreq: 261.63, // C4
      endFreq: 1046.50, // C6
      duration: 0.6,
      attack: 0.2,
      decay: 0.6,
      sustain: 0.7,
      release: 0.2,
      volume: 0.7,
      vibratoFreq: 6,
      vibratoDepth: 20,
      filterFreq: 5000,
      filterSweep: false,
      distortion: 0.0,
    }
  },
  {
    id: 'retro-gameover',
    name: 'Game Over',
    khmerName: 'ចាញ់ហ្គេម',
    category: 'game',
    icon: 'Skull',
    color: 'indigo',
    keyTrigger: 'I',
    params: {
      waveform: 'sawtooth',
      startFreq: 380,
      endFreq: 60,
      duration: 0.85,
      attack: 0.05,
      decay: 0.8,
      sustain: 0.3,
      release: 0.3,
      volume: 0.75,
      vibratoFreq: 12,
      vibratoDepth: 25,
      filterFreq: 1200,
      filterSweep: true,
      distortion: 0.2,
    }
  },

  // UI / App Interaction Sound Effects
  {
    id: 'ui-click',
    name: 'Simple Click',
    khmerName: 'ចុចធម្មតា',
    category: 'ui',
    icon: 'MousePointer',
    color: 'slate',
    keyTrigger: 'A',
    params: {
      waveform: 'sine',
      startFreq: 680,
      endFreq: 540,
      duration: 0.04,
      attack: 0.002,
      decay: 0.95,
      sustain: 0.0,
      release: 0.01,
      volume: 0.45,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 6000,
      filterSweep: false,
      distortion: 0.0,
    }
  },
  {
    id: 'ui-success',
    name: 'Success Alert',
    khmerName: 'ជោគជ័យ',
    category: 'ui',
    icon: 'CheckCircle2',
    color: 'emerald',
    keyTrigger: 'S',
    params: {
      waveform: 'sine',
      startFreq: 523.25, // C5
      endFreq: 783.99, // G5
      duration: 0.22,
      attack: 0.05,
      decay: 0.8,
      sustain: 0.5,
      release: 0.08,
      volume: 0.65,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 5000,
      filterSweep: false,
      distortion: 0.0,
    }
  },
  {
    id: 'ui-error',
    name: 'Error Buzz',
    khmerName: 'កំហុស / បដិសេធ',
    category: 'ui',
    icon: 'XCircle',
    color: 'rose',
    keyTrigger: 'D',
    params: {
      waveform: 'sawtooth',
      startFreq: 140,
      endFreq: 100,
      duration: 0.3,
      attack: 0.02,
      decay: 0.9,
      sustain: 0.4,
      release: 0.08,
      volume: 0.75,
      vibratoFreq: 30,
      vibratoDepth: 20,
      filterFreq: 750,
      filterSweep: false,
      distortion: 0.35,
    }
  },
  {
    id: 'ui-warning',
    name: 'Notification Bell',
    khmerName: 'កណ្ដឹងជូនដំណឹង',
    category: 'ui',
    icon: 'AlertTriangle',
    color: 'amber',
    keyTrigger: 'F',
    params: {
      waveform: 'sine',
      startFreq: 987.77,
      endFreq: 987.77,
      duration: 0.25,
      attack: 0.01,
      decay: 0.6,
      sustain: 0.3,
      release: 0.15,
      volume: 0.55,
      vibratoFreq: 5,
      vibratoDepth: 10,
      filterFreq: 4000,
      filterSweep: false,
      distortion: 0.0,
    }
  },
  {
    id: 'ui-swoosh',
    name: 'Swoosh Transition',
    khmerName: 'កាត់ស្លាយ / រហ័ស',
    category: 'ui',
    icon: 'Wind',
    color: 'sky',
    keyTrigger: 'G',
    params: {
      waveform: 'noise',
      startFreq: 0,
      endFreq: 0,
      duration: 0.28,
      attack: 0.25,
      decay: 0.75,
      sustain: 0.0,
      release: 0.08,
      volume: 0.5,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 2400,
      filterSweep: true,
      distortion: 0.0,
    }
  },
  {
    id: 'ui-pop',
    name: 'Pop Bubble',
    khmerName: 'ពពុះសាប៊ូ',
    category: 'ui',
    icon: 'Flame',
    color: 'pink',
    keyTrigger: 'H',
    params: {
      waveform: 'sine',
      startFreq: 250,
      endFreq: 850,
      duration: 0.1,
      attack: 0.01,
      decay: 0.9,
      sustain: 0.1,
      release: 0.03,
      volume: 0.7,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 3000,
      filterSweep: false,
      distortion: 0.0,
    }
  },

  // Beat & Musical Elements Sound Effects
  {
    id: 'music-kick',
    name: 'Drum Kick Bass',
    khmerName: 'ស្គរធំ Kick Bass',
    category: 'music',
    icon: 'Drum',
    color: 'fuchsia',
    keyTrigger: 'Z',
    params: {
      waveform: 'sine',
      startFreq: 140,
      endFreq: 35,
      duration: 0.2,
      attack: 0.005,
      decay: 0.85,
      sustain: 0.0,
      release: 0.05,
      volume: 1.0,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 250,
      filterSweep: true,
      distortion: 0.15,
    }
  },
  {
    id: 'music-snare',
    name: 'Drum Snare Hit',
    khmerName: 'ស្គរតូច Snare',
    category: 'music',
    icon: 'Tv',
    color: 'violet',
    keyTrigger: 'X',
    params: {
      waveform: 'noise',
      startFreq: 0,
      endFreq: 0,
      duration: 0.16,
      attack: 0.005,
      decay: 0.9,
      sustain: 0.02,
      release: 0.04,
      volume: 0.75,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 1800,
      filterSweep: true,
      distortion: 0.2,
    }
  },
  {
    id: 'music-hihat',
    name: 'Hi-Hat Cymbal',
    khmerName: 'ស្គរ Hi-Hat',
    category: 'music',
    icon: 'Music',
    color: 'blue',
    keyTrigger: 'C',
    params: {
      waveform: 'noise',
      startFreq: 0,
      endFreq: 0,
      duration: 0.04,
      attack: 0.001,
      decay: 0.99,
      sustain: 0.0,
      release: 0.02,
      volume: 0.55,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 9000,
      filterSweep: true,
      distortion: 0.0,
    }
  },
  {
    id: 'music-synthpluck',
    name: 'Retro Pluck Note',
    khmerName: 'សំឡេង Synth Pluck',
    category: 'music',
    icon: 'Waves',
    color: 'teal',
    keyTrigger: 'V',
    params: {
      waveform: 'triangle',
      startFreq: 440, // A4
      endFreq: 440,
      duration: 0.14,
      attack: 0.005,
      decay: 0.4,
      sustain: 0.0,
      release: 0.04,
      volume: 0.7,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 1200,
      filterSweep: true,
      distortion: 0.0,
    }
  },
  {
    id: 'music-subbass',
    name: 'Deep Sub-Bass',
    khmerName: 'បាសជ្រៅ Sub-Bass',
    category: 'music',
    icon: 'Cloud',
    color: 'cyan',
    keyTrigger: 'B',
    params: {
      waveform: 'sine',
      startFreq: 55, // A1
      endFreq: 40,
      duration: 0.5,
      attack: 0.08,
      decay: 0.8,
      sustain: 0.8,
      release: 0.15,
      volume: 0.85,
      vibratoFreq: 0,
      vibratoDepth: 0,
      filterFreq: 120,
      filterSweep: false,
      distortion: 0.1,
    }
  }
];
